version: '3'
name: p7project
volumes:
  cuda:
  pip:

services:
  backend:
    image: ghcr.io/p72024/p7project/backend:latest
    runtime: nvidia
    ports:
      - "3000:3000"
    environment:
      - ENV=production
    volumes:
      - cuda:/usr/local/cuda
      - pip:/root/.cache/pip
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  client:
    image: ghcr.io/p72024/p7project/client:latest
    depends_on:
      - backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: unless-stopped
    
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    env_file: "secrets.env"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 86400 --cleanup -x watchtower
    restart: unless-stopped

networks:
  app-network:
