services:
  api:
    build:
      context: .
    restart: unless-stopped
    ports:
      - 5000:5000
    env_file:
      - ./secrets.env
    networks:
      -  api
    # depends_on:
    #   - db
  db:
    image: postgres:14.3
    restart: unless-stopped
    ports:
      - 5432
    volumes:
    env_file:
      - ./secrets.env
    networks:
      - api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5