version: '0.0.1'
name: p7project
volumes:
  pip:
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - ENV=development
    volumes:
      - pip:/root/.cache/pip

  client:
    build: ./client
    depends_on:
      - backend
    ports:
      - "80:80"
