version: '0.0.1'
services:
  backend:
    restart: unless-stopped
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - ENV=development
    networks:
      - app-network

  client:
    restart: unless-stopped
    build: ./client
    depends_on:
      - backend
    ports:
      - "8010:8010"
    networks:
      - app-network

networks:
  app-network:
