version: '3'
name: p7project
volumes:
  pip:
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - ENV=development
    volumes:
      - pip:/root/.cache/pip
    networks:
      - app-network

  client:
    build: ./client
    depends_on:
      - backend
    ports:
      - "8010:8010"
    networks:
      - app-network

networks:
  app-network:
