version: '3'
name: p7project
volumes:
  pip:
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - ENV=development
    volumes:
      - pip:/root/.cache/pip
    networks:
      - app-network
    restart: unless-stopped

  client:
    build: ./client
    depends_on:
      - backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
