name: Build Image

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  ghcr-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out

      # - uses: crazy-max/ghaction-docker-meta@v1
      #   name: Docker meta
      #   id: docker_meta
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ github.repository }}
      #     tag-sha: true
      #     tag-edge: false
      #     tag-latest: true

      # - uses: docker/setup-qemu-action@v3
      #   name: Set up QEMU

      # - uses: docker/setup-buildx-action@v3
      #   name: Set up Docker Buildx

      - uses: docker/login-action@v3
        name: Login to GitHub Container Registry (ghcr.io)
        with:
          registry: ${{ env.REGISTRY }}
          # The login of the user that initiated the workflow run.
          username: ${{ github.actor }}
          # A token to authenticate on behalf of the GitHub App installed on your repository.
          password: ${{ github.token }}

      - uses: docker/build-push-action@v5
        # Allows us to retrieve the output from the build
        id: docker_image_build
        with:
          # The context is NOT relative to the Dockerfile location but the repository root
          context: .
          push: false
          tags: ${{ env.REGISTRY }}/${{ github.repository }},${{ github.event.release.target_commitish }}
          # file: ./docker-prod.yml