name: Build Image

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  ghcr-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out
        with:
            submodules: true
            token: ${{ github.token }}

      - uses: docker/login-action@v3
        name: Login to GitHub Container Registry (ghcr.io)
        with:
          registry: ${{ env.REGISTRY }}
          # The login of the user that initiated the workflow run.
          username: ${{ github.actor }}
          # A token to authenticate on behalf of the GitHub App installed on your repository.
          password: ${{ github.token }}

      - name: Build Docker image and push to DockerHub
        # Allows us to retrieve the output from the build
        id: docker_image_build
        run:  |
            docker compose -f docker-prod.yml build
            docker compose -f docker-prod.yml push
      
      - name: Check images
        run: docker image ls