name: Build Image

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  ghcr-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out
        with:
            submodules: 'true'
            token: ${{ github.token }}

      - uses: docker/setup-qemu-action@v3
        name: Set up QEMU

      - uses: docker/setup-buildx-action@v3
        name: Set up Docker Buildx

      - uses: docker/login-action@v3
        name: Login to GitHub Container Registry (ghcr.io)
        with:
          registry: ${{ env.REGISTRY }}
          # The login of the user that initiated the workflow run.
          username: ${{ github.actor }}
          # A token to authenticate on behalf of the GitHub App installed on your repository.
          password: ${{ github.token }}

      - name: Build and push docker image
        run: |
            docker compose -f docker-prod.yml build
            docker tag p7project-backend ${{ env.REGISTRY }}/p72024/p7project/backend:${{ github.sha }}
            docker tag p7project-client ${{ env.REGISTRY }}/p72024/p7project/client:${{ github.sha }}
            docker push ${{ env.REGISTRY }}/p72024/p7project/backend:${{ github.sha }}
            docker push ${{ env.REGISTRY }}/p72024/p7project/client:${{ github.sha }}
