
name: Update Submodules from Submodule Repos

on:
  repository_dispatch:
    types: [update_submodules]

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout parent repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update submodules
        run: |
          git submodule init
          git submodule update --remote --merge 

      - name: Commit and push updated submodules
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automatically updated submodules after submodule changes"
          git push origin main
        continue-on-error: true
